---

- hosts: zk*
  sudo: yes
  pre_tasks:
    - lineinfile: dest=/etc/hosts state=absent regexp="^127.0.1.1" #If found, zookeeper binds to localhost address

- hosts: zk1*
  vars:
    myid: 1
    java_versions: oracle-jdk7-installer
  roles:
    - ansible-zookeeper

- hosts: zk2*
  vars:
    myid: 2
    java_versions: oracle-jdk7-installer
  roles:
    - ansible-zookeeper

- hosts: zk3*
  vars:
    myid: 3
    java_versions: oracle-jdk7-installer
  roles:
    - ansible-zookeeper
